[lint]
extend-ignore = ["EXE002"]

[lint.per-file-ignores]
"apps/accounts/migrations/*.py" = ["RUF012"]
"apps/catalog/admin.py" = ["RUF012"]
"apps/catalog/migrations/*.py" = ["RUF012"]
"apps/catalog/models.py" = ["RUF012"]
"apps/cart/migrations/*.py" = ["RUF012"]
"apps/cart/models.py" = ["RUF012"]
"apps/orders/migrations/*.py" = ["RUF012"]
