# Generated by Django 6.0.7 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("catalog", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(blank=True, upload_to="products/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
