# Generated by Django 6.0.7 on 2026-08-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("laptop", "Laptop"), ("mobile", "Mobile")],
                default="laptop",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="LaptopSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processor", models.CharField(max_length=120)),
                ("ram_gb", models.PositiveSmallIntegerField()),
                ("storage_gb", models.PositiveIntegerField()),
                (
                    "display_size_inches",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                ("graphics", models.CharField(blank=True, max_length=120)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laptop_specification",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MobileSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ram_gb", models.PositiveSmallIntegerField()),
                ("storage_gb", models.PositiveIntegerField()),
                ("camera_megapixels", models.PositiveSmallIntegerField()),
                (
                    "network",
                    models.CharField(
                        choices=[("4g", "4G"), ("5g", "5G")], max_length=2
                    ),
                ),
                ("battery_mah", models.PositiveIntegerField()),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_specification",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
    ]
