# Generated by Django 6.0.7 on 2026-08-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_review_ratings(apps, schema_editor):
    ProductRating = apps.get_model("catalog", "ProductRating")
    ProductReview = apps.get_model("catalog", "ProductReview")

    for review in ProductReview.objects.filter(
        parent__isnull=True, rating__isnull=False
    ).iterator():
        ProductRating.objects.update_or_create(
            product_id=review.product_id,
            user_id=review.user_id,
            defaults={"score": review.rating},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_productreview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.PositiveSmallIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(copy_review_ratings, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="productreview",
            name="catalog_review_rating_between_one_and_five",
        ),
        migrations.RemoveConstraint(
            model_name="productreview",
            name="catalog_one_root_review_per_customer",
        ),
        migrations.RemoveField(model_name="productreview", name="rating"),
        migrations.AddConstraint(
            model_name="productrating",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 1), ("score__lte", 5)),
                name="catalog_rating_between_one_and_five",
            ),
        ),
        migrations.AddConstraint(
            model_name="productrating",
            constraint=models.UniqueConstraint(
                fields=("product", "user"),
                name="catalog_one_rating_per_customer",
            ),
        ),
    ]
