# Generated by Django 6.0.7 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_productrating_remove_productreview_rating_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="moderation_status",
            field=models.CharField(
                choices=[("approved", "Approved"), ("rejected", "Rejected")],
                default="approved",
                max_length=16,
            ),
        ),
    ]
