# Generated by Django 6.0.7 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("catalog", "0006_productreview_moderation_status")]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, upload_to="categories/%Y/%m/"),
        ),
    ]
