# Generated by Django 6.0.7 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0002_otpchallenge")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=80),
        )
    ]
