# Generated by Django 6.0.7 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0003_user_display_name")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="home_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="province",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
